"""Add response metadata fields

Revision ID: 0a2a8a436b56
Revises: a826548dbdb5
Create Date: 2026-07-16 14:34:32.999281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a2a8a436b56'
down_revision: Union[str, Sequence[str], None] = 'a826548dbdb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('response_type', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('language', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('history_used', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('cached', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('processing_time', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('confidence', sa.Float(), nullable=True))
    op.drop_column('messages', 'response_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('response_time', sa.INTEGER(), nullable=True))
    op.drop_column('messages', 'confidence')
    op.drop_column('messages', 'processing_time')
    op.drop_column('messages', 'cached')
    op.drop_column('messages', 'history_used')
    op.drop_column('messages', 'language')
    op.drop_column('messages', 'response_type')
    # ### end Alembic commands ###
