"""Add_cost_and_response_id

Revision ID: a826548dbdb5
Revises: c5e79f3ea8cd
Create Date: 2026-07-16 14:15:52.888225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a826548dbdb5'
down_revision: Union[str, Sequence[str], None] = 'c5e79f3ea8cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('cost', sa.Float(), nullable=True))
    op.add_column('messages', sa.Column('response_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'response_id')
    op.drop_column('messages', 'cost')
    # ### end Alembic commands ###
